# Generated by Django 6.0.6 on 2026-07-01 11:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.BigIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_by', models.CharField(max_length=255)),
                ('shipping_address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('subtotal', models.BigIntegerField()),
                ('amount', models.BigIntegerField()),
                ('order_status', models.CharField(choices=[('PENDING_ORDER', 'PENDING_ORDER'), ('ORDER_RECEIVED', 'ORDER_RECEIVED'), ('ORDER_CONFIRMED', 'ORDER_CONFIRMED'), ('ORDER_PROCESSED', 'ORDER_PROCESSED'), ('ORDER_SHIPPED', 'ORDER_SHIPPED'), ('ORDER_RETURNED', 'ORDER_RETURNED'), ('ORDER_DELIVERED', 'ORDER_DELIVERED')], default='PENDING_ORDER', max_length=100)),
                ('payment_method', models.CharField(choices=[('paystack', 'paystack'), ('flutterwave', 'flutterwave'), ('cash_on_delivery', 'cash_on_delivery'), ('paypal', 'paypal')], default='paystack', max_length=50)),
                ('payment_completed', models.BooleanField(default=False)),
                ('ref', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.cart')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.BigIntegerField()),
                ('discount_price', models.BigIntegerField(blank=True, null=True)),
                ('main', models.ImageField(upload_to='products')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='products')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='products')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='products')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='products')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='products')),
                ('size', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('review', models.TextField()),
                ('rating', models.IntegerField()),
                ('in_stock', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('product_code', models.UUIDField(default=uuid.uuid4, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.category')),
            ],
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.product')),
            ],
        ),
    ]
